version: "3.7"

services:
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=graphs
    restart: always
    privileged: true
  dashboard:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8000:8081"
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: root
       ME_CONFIG_MONGODB_SERVER: db
       ME_CONFIG_MONGODB_PORT: "27017"
    privileged: true
    links:
      - db
    depends_on:
      - db
    restart: always

