apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  labels:
    app: mongodb
  namespace: default

data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: cm9vdA==
